name = "1122-amazon-sp-api-bridge"
main = "worker.js"
compatibility_date = "2026-08-31"
workers_dev = true

[[kv_namespaces]]
binding = "PRODUCT_STATE"
id = "daf3ad0cb59b4ada940e5f02405d4351"

[[d1_databases]]
binding = "CORE_DB"
database_name = "1122-core"
database_id = "00076b01-471f-40e6-bf49-57cfc07facc8"
