import assert from 'node:assert/strict';
import { runAgent7ToS03 } from '../a7-a1-s03-runtime.js';
import { runAgent7ToS04Priority } from '../a7-a1-s04-priority-runtime.js';
function makeInput(){return{input_mode:'simulated',request_id:'REQ-A7-PRIORITY-001',scope:{scope_type:'product',scope_id:'PROD-7',product_id:'PROD-7',asin:'B0A7TEST01',marketplace:'US'},inventory_snapshot:{snapshot_id:'INV-A7-P-001',observed_at:'2026-09-04T22:00:00.000Z',available_units:120,freshness:'fresh'},demand_baseline:{baseline_id:'DEMAND-A7-P-001',daily_units:20,freshness:'fresh'},lead_time_days:8,safety_stock_days:4,evidence_refs:['sim://inventory/PROD-7/INV-A7-P-001','sim://demand/PROD-7/DEMAND-A7-P-001']};}
function loaded(d,e=null){let data;if(d==='C01')data={product_id:'PROD-7',asin:'B0A7TEST01'};else if(d==='C02')data={current_state:{inventory_state:'low_coverage'}};else if(d==='C03')data={active_plan:{primary_goal:'Assess supply risk without writes.'}};else if(d==='C05')data={recent_events:e?[e]:[]};else data={domain:d,product_id:'PROD-7'};return{status:'loaded',freshness:'fresh',as_of:'2026-09-04T22:00:00.000Z',source:'simulated-contract-context',item_count:Array.isArray(data.recent_events)?data.recent_events.length:1,refs:[`test:${d}:PROD-7`],data};}const context=(e=null)=>Object.fromEntries(Array.from({length:10},(_,i)=>`C${String(i+1).padStart(2,'0')}`).map(d=>[d,loaded(d,e)]));const base={generatedAt:'2026-09-04T22:00:01.000Z',receivedAt:'2026-09-04T22:00:02.000Z',mappedAt:'2026-09-04T22:00:03.000Z',currentTime:'2026-09-04T22:00:04.000Z',knownProductIds:['PROD-7']};const probe=runAgent7ToS03(makeInput(),{...base,availableContext:context()});const e=probe.canonicalEvent;const se={event_id:e.event_id,event_type:e.event_type,severity:e.severity,summary:e.summary,metrics:e.metrics,occurred_at:e.occurred_at,requires_decision_by:e.requires_decision_by??null};const options={...base,availableContext:context(se)};
const ready=await runAgent7ToS04Priority(makeInput(),options);assert.equal(ready.status,'priority_ready');assert.equal(ready.nextAction,'continue_to_decision_formation');assert.equal(ready.readOnly,true);assert.equal(ready.permissionGranted,false);assert.equal(ready.executionAuthorized,false);assert.equal(ready.productionWriteAuthorized,false);assert.equal(ready.canonicalEvent.source_agent,'Agent-7');assert.equal(ready.canonicalEvent.event_type,'LOW_COVERAGE');assert.equal(ready.priorityCandidate.status,'candidate_ready');assert.equal(ready.priorityResult.status,'ranking_ready');assert.equal(ready.priorityResult.rankedDecisionItems.length,1);assert.equal(ready.priorityResult.rankedDecisionItems[0].rank,1);assert.equal(Object.prototype.hasOwnProperty.call(ready,'decisionCandidate'),false);
for(const [k,v] of [['permissionGranted',true],['purchaseOrder',{units:10}],['transferOrder',{units:10}]]){const b=await runAgent7ToS04Priority({...makeInput(),[k]:v},options);assert.equal(b.status,'blocked');assert.ok(b.reasons.includes(`privilege_injection_${k}`));assert.equal(b.priorityResult,null);}
const missing=await runAgent7ToS04Priority(makeInput(),{...base,availableContext:context()});assert.equal(missing.status,'needs_information');assert.equal(missing.priorityResult,null);
console.log('Agent-7 S04 read-only Priority contract: PASS');
