import assert from 'node:assert/strict';
import { runAgent8EmergingUptrend } from '../a8-market-trend-runtime.js';
import { runAgent8FullReadonly } from '../a8-full-readonly-runtime.js';
function makeInput(){return{input_mode:'simulated',request_id:'REQ-A8-FULL-001',scope:{scope_type:'global',scope_id:'US-MAHJONG',marketplace:'US'},subject:'american mahjong',observed_at:'2026-09-05T03:20:00.000Z',baseline_index:100,current_index:118,seasonality_explained:false,event_driven:false,signals:[{signal_type:'search_demand',direction:'up',freshness:'fresh',source_ref:'sim://search/us-mahjong'},{signal_type:'category_velocity',direction:'up',freshness:'fresh',source_ref:'sim://category/us-mahjong'}]};}
const base={generatedAt:'2026-09-05T03:20:01.000Z',receivedAt:'2026-09-05T03:20:02.000Z',mappedAt:'2026-09-05T03:20:03.000Z',currentTime:'2026-09-05T03:20:04.000Z'};
const probe=runAgent8EmergingUptrend(makeInput(),base);const e=probe.normalizedEvent.canonicalEvent;const se={event_id:e.event_id,event_type:e.event_type,severity:e.severity,summary:e.summary,metrics:e.metrics,occurred_at:e.occurred_at,requires_decision_by:e.requires_decision_by??null};
function loaded(d){let data;if(d==='C01')data={scope_id:'US-MAHJONG',marketplace:'US',subject:'american mahjong'};else if(d==='C02')data={current_state:{market_trend:'emerging_uptrend',observed_at:'2026-09-05T03:20:00.000Z'}};else if(d==='C03')data={active_plan:{primary_goal:'Review market trend without production writes.'}};else if(d==='C05')data={recent_events:[se]};else data={domain:d,scope_id:'US-MAHJONG'};return{status:'loaded',freshness:'fresh',as_of:'2026-09-05T03:20:00.000Z',source:'simulated-contract-context',item_count:Array.isArray(data.recent_events)?data.recent_events.length:1,refs:[`test:${d}:US-MAHJONG`],data};}
const context=()=>Object.fromEntries(Array.from({length:10},(_,i)=>`C${String(i+1).padStart(2,'0')}`).map(d=>[d,loaded(d)]));
const r=await runAgent8FullReadonly(makeInput(),{...base,availableContext:context()});assert.equal(r.status,'approval_pending');assert.equal(r.nextAction,'await_verified_human_approval');assert.equal(r.stage,'PermissionBoundary');assert.equal(r.readOnly,true);assert.equal(r.approvalGranted,false);assert.equal(r.permissionGranted,false);assert.equal(r.taskAuthorized,false);assert.equal(r.executionAuthorized,false);assert.equal(r.dispatchAuthorized,false);assert.equal(r.productionWriteAuthorized,false);assert.equal(r.canonicalEvent.source_agent,'Agent-8');assert.equal(r.canonicalEvent.event_type,'EMERGING_UPTREND');assert.equal(r.canonicalEvent.scope_type,'global');assert.equal(r.s01.next_action,'continue_to_S02');assert.ok(['ready','ready_with_gaps'].includes(r.s02.status));assert.equal(r.s03.next_action,'continue_to_decision_item_builder');assert.equal(r.builder.next_action,'continue_to_S04');assert.equal(r.s04.nextAction,'continue_to_S04');assert.equal(r.priorityResult.nextAction,'continue_to_decision_formation');assert.equal(r.formation.nextAction,'continue_to_task_draft_generation');assert.equal(r.taskDraftResult.nextAction,'continue_to_approval_gate');assert.equal(r.approvalGateResult.nextAction,'await_human_approval');assert.equal(r.permissionDecisionResult.status,'blocked');assert.ok(r.permissionDecisionResult.reasons.includes('approval_record_count_mismatch'));assert.deepEqual(r.permissionDecisionResult.permissionDecisions,[]);
const missing=await runAgent8FullReadonly(makeInput(),{...base});assert.equal(missing.stage,'S02');assert.equal(missing.status,'blocked');assert.equal(missing.permissionGranted,false);
const forged=await runAgent8FullReadonly({...makeInput(),priceAction:{}},{...base,availableContext:context()});assert.equal(forged.status,'blocked');assert.equal(forged.stage,'domain');assert.equal(forged.productionWriteAuthorized,false);
console.log('Agent-8 full fail-closed read-only chain contract: PASS');
