import assert from 'node:assert/strict';
import { runAgent8EmergingUptrend } from '../a8-market-trend-runtime.js';
function makeInput(){return{input_mode:'simulated',request_id:'REQ-A8-001',scope:{scope_type:'global',scope_id:'US-MAHJONG',marketplace:'US'},subject:'american mahjong',observed_at:'2026-09-05T03:20:00.000Z',baseline_index:100,current_index:118,seasonality_explained:false,event_driven:false,signals:[{signal_type:'search_demand',direction:'up',freshness:'fresh',source_ref:'sim://search/us-mahjong'},{signal_type:'category_velocity',direction:'up',freshness:'fresh',source_ref:'sim://category/us-mahjong'}]};}
const options={generatedAt:'2026-09-05T03:20:01.000Z',receivedAt:'2026-09-05T03:20:02.000Z',mappedAt:'2026-09-05T03:20:03.000Z'};
const r=runAgent8EmergingUptrend(makeInput(),options);assert.equal(r.status,'event_and_response_ready');assert.equal(r.nextAction,'stop_before_A1_intake');assert.equal(r.readOnly,true);assert.equal(r.approvalGranted,false);assert.equal(r.permissionGranted,false);assert.equal(r.taskAuthorized,false);assert.equal(r.executionAuthorized,false);assert.equal(r.dispatchAuthorized,false);assert.equal(r.productionWriteAuthorized,false);assert.equal(r.marketTrendEvent.agent_id,'Agent-8');assert.equal(r.marketTrendEvent.trend_type,'EMERGING_UPTREND');assert.equal(r.marketTrendEvent.status,'candidate');assert.equal(r.marketTrendEvent.direction,'up');assert.equal(r.marketTrendEvent.supporting_signals.length,2);assert.equal(r.normalizedEvent.status,'normalized');assert.equal(r.normalizedEvent.canonicalEvent.source_agent,'Agent-8');assert.equal(r.normalizedEvent.canonicalEvent.event_type,'EMERGING_UPTREND');assert.equal(r.normalizedEvent.canonicalEvent.scope_type,'global');
const oneSignal=makeInput();oneSignal.signals=oneSignal.signals.slice(0,1);const b1=runAgent8EmergingUptrend(oneSignal,options);assert.equal(b1.status,'blocked');assert.ok(b1.reasons.includes('insufficient_independent_signals'));
const sameType=makeInput();sameType.signals[1].signal_type='search_demand';const b2=runAgent8EmergingUptrend(sameType,options);assert.equal(b2.status,'blocked');assert.ok(b2.reasons.includes('insufficient_signal_breadth'));
const seasonal=makeInput();seasonal.seasonality_explained=true;const b3=runAgent8EmergingUptrend(seasonal,options);assert.equal(b3.status,'blocked');assert.ok(b3.reasons.includes('seasonality_not_excluded'));
const weak=makeInput();weak.current_index=105;const o=runAgent8EmergingUptrend(weak,options);assert.equal(o.status,'no_material_uptrend');assert.equal(o.nextAction,'observe');assert.equal(o.productionWriteAuthorized,false);
for(const [k,v] of [['approvalGranted',true],['priceAction',{}],['adAction',{}],['inventoryAction',{}],['promotionAction',{}],['listingAction',{}]]){const b=runAgent8EmergingUptrend({...makeInput(),[k]:v},options);assert.equal(b.status,'blocked');assert.ok(b.reasons.includes(`privilege_injection_${k}`));assert.equal(b.productionWriteAuthorized,false);}
console.log('Agent-8 read-only market trend runtime contract: PASS');
