import assert from 'node:assert/strict';
import { runAgent9StableTrafficCvrDrop, runAgent10ReferencePriceLost, runAgent11NegativeReviewSurge, runAgent12ProductComplianceGap, runAgent13CrossDomainSynergy } from '../a9-a13-readonly-domain-runtimes.js';
import { runAgent9FullReadonly, runAgent10FullReadonly, runAgent11FullReadonly, runAgent12FullReadonly, runAgent13FullReadonly } from '../a9-a13-full-readonly-runtimes.js';
const observed='2026-09-05T04:00:00.000Z';
const scope=(id)=>({scope_type:'product',scope_id:id,product_id:id,asin:`B0${id.replace('PROD-','A')}TEST`,marketplace:'US'});
const common=(id)=>({input_mode:'simulated',request_id:`REQ-${id}`,scope:scope(id),observed_at:observed,evidence_refs:[`sim://evidence/${id}/1`,`sim://evidence/${id}/2`]});
const inputs={
  a9:{...common('PROD-9'),baseline_window:{window_id:'A9-B',sessions:1000,orders:100,freshness:'fresh'},current_window:{window_id:'A9-C',sessions:1020,orders:70,freshness:'fresh'}},
  a10:{...common('PROD-10'),price_snapshot:{snapshot_id:'A10-P',current_price:79.99,expected_reference_price:99.99,reference_price_visible:false,freshness:'fresh'}},
  a11:{...common('PROD-11'),baseline_window:{window_id:'A11-B',review_count:100,negative_review_count:10,freshness:'fresh'},current_window:{window_id:'A11-C',review_count:100,negative_review_count:20,freshness:'fresh'}},
  a12:{...common('PROD-12'),marketplace:'US',rule_refs:['RULE-12-A'],missing_evidence:['required_document_A']},
  a13:{...common('PROD-13'),hypothesis:'Conversion and market-trend evidence may support a cross-domain growth test.',source_agent_refs:['Agent-8','Agent-9'],constraint_status:'clear'},
};
const pairs=[
  ['Agent-9','CVR_DROP_WITH_STABLE_TRAFFIC',runAgent9StableTrafficCvrDrop,runAgent9FullReadonly,inputs.a9],
  ['Agent-10','REFERENCE_PRICE_LOST',runAgent10ReferencePriceLost,runAgent10FullReadonly,inputs.a10],
  ['Agent-11','NEGATIVE_REVIEW_SURGE',runAgent11NegativeReviewSurge,runAgent11FullReadonly,inputs.a11],
  ['Agent-12','PRODUCT_COMPLIANCE_GAP',runAgent12ProductComplianceGap,runAgent12FullReadonly,inputs.a12],
  ['Agent-13','CROSS_DOMAIN_SYNERGY',runAgent13CrossDomainSynergy,runAgent13FullReadonly,inputs.a13],
];
function contextFor(input,event){function loaded(d){let data;if(d==='C01')data={product_id:input.scope.product_id,asin:input.scope.asin,title:`Test ${input.scope.product_id}`};else if(d==='C02')data={current_state:{read_only_signal:true,observed_at:observed}};else if(d==='C03')data={active_plan:{primary_goal:'Review evidence without production writes.'}};else if(d==='C05')data={recent_events:[{event_id:event.event_id,event_type:event.event_type,severity:event.severity,summary:event.summary,metrics:event.metrics,occurred_at:event.occurred_at,requires_decision_by:event.requires_decision_by??null}]};else data={domain:d,product_id:input.scope.product_id};return{status:'loaded',freshness:'fresh',as_of:observed,source:'simulated-contract-context',item_count:Array.isArray(data.recent_events)?data.recent_events.length:1,refs:[`test:${d}:${input.scope.product_id}`],data};}return Object.fromEntries(Array.from({length:10},(_,i)=>`C${String(i+1).padStart(2,'0')}`).map(d=>[d,loaded(d)]));}
for(const [agent,eventType,domainFn,fullFn,input] of pairs){const d=domainFn(input);assert.equal(d.status,'event_and_response_ready',`${agent} domain runtime`);assert.equal(d.readOnly,true);assert.equal(d.productionWriteAuthorized,false);const e=d.normalizedEvent.canonicalEvent;assert.equal(e.source_agent,agent);assert.equal(e.event_type,eventType);const r=await fullFn(input,{currentTime:observed,knownProductIds:[input.scope.product_id],availableContext:contextFor(input,e)});assert.equal(r.status,'approval_pending',`${agent} full status`);assert.equal(r.nextAction,'await_verified_human_approval');assert.equal(r.stage,'PermissionBoundary');assert.equal(r.readOnly,true);assert.equal(r.approvalGranted,false);assert.equal(r.permissionGranted,false);assert.equal(r.taskAuthorized,false);assert.equal(r.executionAuthorized,false);assert.equal(r.dispatchAuthorized,false);assert.equal(r.productionWriteAuthorized,false);assert.equal(r.canonicalEvent.source_agent,agent);assert.equal(r.canonicalEvent.event_type,eventType);assert.equal(r.s01.next_action,'continue_to_S02');assert.ok(['ready','ready_with_gaps'].includes(r.s02.status));assert.equal(r.s03.next_action,'continue_to_decision_item_builder');assert.equal(r.builder.next_action,'continue_to_S04');assert.equal(r.s04.nextAction,'continue_to_S04');assert.equal(r.priorityResult.nextAction,'continue_to_decision_formation');assert.equal(r.formation.nextAction,'continue_to_task_draft_generation');assert.equal(r.taskDraftResult.nextAction,'continue_to_approval_gate');assert.equal(r.approvalGateResult.nextAction,'await_human_approval');assert.equal(r.permissionDecisionResult.status,'blocked');assert.ok(r.permissionDecisionResult.reasons.includes('approval_record_count_mismatch'));assert.deepEqual(r.permissionDecisionResult.permissionDecisions,[]);const b=await fullFn({...input,productionWriteAuthorized:true},{currentTime:observed,knownProductIds:[input.scope.product_id],availableContext:contextFor(input,e)});assert.equal(b.status,'blocked');assert.equal(b.productionWriteAuthorized,false);}
console.log('Agent-9 through Agent-13 full fail-closed read-only chains: PASS');
