(() => {
  // 仅转换前端约定的状态字面量；接口、用户和抓取数据中的未知内容保持原样。
  const knownValues = Object.freeze({
    LIVE_READ: '实时只读',
    LIVE_D1_READ: '实时只读',
    LIVE_EMPTY: '实时数据为空',
    PARTIAL_LIVE: '部分实时',
    DESIGN_ONLY: '仅有设计',
    CONTRACT_READY: '页面契约已就绪',
    TRACKED: '持续跟踪',
    SNAPSHOT_FALLBACK: '快照数据',
    API: '接口读取',
    D1: '数据存储',
    RUNTIME_BOUND: '运行环境已绑定',
    'RUNTIME BOUND': '运行环境已绑定',
    SEMANTIC_VERIFIED: '语义已验证',
    SEMANTIC_PENDING: '语义待验证',
    NEEDS_DATA: '待补充数据',
    'NEEDS DATA': '待补充数据',
    PLAN_NOT_INGESTED: '计划数据未接入',
    'PLAN NOT INGESTED': '计划数据未接入',
    BRIEF_NOT_INGESTED: '每日简报数据未接入',
    'BRIEF NOT INGESTED': '每日简报数据未接入',
    NO_ACTIVE_PLAN: '暂无有效计划',
    NO_BRIEF: '暂无每日简报',
    PLAN_READ_MODEL: '计划读模型可用',
    'PLAN READ MODEL': '计划读模型可用',
    BRIEF_READ_MODEL: '每日简报读模型可用',
    'BRIEF READ MODEL': '每日简报读模型可用',
    SOURCE_PENDING: '数据待确认',
    AUTH_REQUIRED: '需要授权',
    SESSION_ACTIVE: '会话已启用',
    PROTECTED_ACTION: '受保护操作',
    SESSION_GATE_READY: '登录校验已就绪',
    WRITE_GATE_NOT_CONFIGURED: '写入门禁未配置',
    EXECUTION_LOCKED: '执行已锁定',
    REQUEST_FAILED: '请求失败',
    WRITE_FAILED: '写入失败',
    UNKNOWN_ERROR: '未知错误',
    LIVE: '实时可用',
    CONNECTED: '已连接',
    DISCONNECTED: '未连接',
    SUCCESS: '成功',
    READY: '已就绪',
    FRESH: '最新',
    VERIFIED: '已验证',
    ALLOWED: '已允许',
    CONFIRMED: '已确认',
    POSITIVE: '正向',
    LOW: '低',
    MEDIUM: '中',
    HIGH: '高',
    TRUE: '是',
    FALSE: '否',
    PENDING: '待处理',
    PENDING_APPROVAL: '等待审批',
    CHECKING: '检查中',
    LOADING: '加载中',
    UNKNOWN: '未知',
    ERROR: '错误',
    FAIL: '失败',
    FAILED: '失败',
    BLOCK: '已阻止',
    BLOCKED: '已阻止',
    STALE: '已过期',
    NONCOMPLIANT: '不合规',
    WARNING: '提醒',
    WARN: '提醒',
    DEGRADED: '服务降级',
    NOT_CONFIGURED: '未配置',
    NOT_ENABLED: '未启用',
    AVAILABLE: '可用',
    NOT_AVAILABLE: '暂不可用',
    UNAVAILABLE: '暂不可用',
    MISSING: '缺失',
    NO_DATA: '暂无数据',
    NOT_INGESTED: '数据未接入',
    READ_ONLY: '只读',
    APPROVAL_REQUIRED: '需要审批',
    ACTIVE: '启用中',
    INACTIVE: '未启用',
    ENABLED: '已启用',
    DISABLED: '已停用',
    PAUSED: '已暂停',
    ARCHIVED: '已归档',
    PARTICIPATING: '已参与',
    HEALTHY: '健康',
    SUCCEEDED: '已完成',
    CLASSIFYING: '分类中',
    CLASSIFICATION_PENDING: '等待分类',
    INITIALIZED: '已初始化',
    FALLBACK: '备用数据',
    POLICY_EVIDENCE: '政策证据',
    POLICY_DIFF: '政策差异',
    POLICY: '政策知识',
    VERIFIED_ALLOWED: '已验证且允许',
    DISCOVERED: '已发现',
    P0: '紧急',
    P1: '高优先级',
    P2: '中优先级',
    P3: '低优先级',
    SOURCE_ONLY: '仅有来源',
    VALIDATED: '已校验',
    DERIVED: '推导结果',
    OBSERVED: '已观察',
    CONFLICTING: '存在冲突',
    CONDITIONAL: '有条件适用',
    DISCOVERY: '探索中',
    SEEDED: '已预置',
    MARKET_PATTERN: '市场玩法',
    OPERATING_METHOD: '运营方法',
    PRODUCT_KNOWLEDGE: '产品经营知识',
    ADVERTISING_KNOWLEDGE: '广告知识',
    PRICING_KNOWLEDGE: '价格促销知识',
    CONTENT_KNOWLEDGE: '商品内容知识',
    CASE_LESSON: '案例复盘',
    SYSTEM_ENGINEERING: '系统工程',
    DATA_DEFINITION: '数据定义',
    DECISION_RULE: '决策规则',
    marketplaces: '站点覆盖',
    products: '产品数据',
    'product-identity': '产品标识',
    inventory: '库存',
    sales: '销售',
    traffic: '流量',
    finance: '财务',
    'market-intelligence': '市场情报',
    keywords: '关键词',
    competitors: '竞品',
    profiles: '广告账户',
    campaigns: '广告活动',
    'ad-groups': '广告组',
    oauth: '授权',
    tools: '工具服务'
  });

  function mapKnownValue(value) {
    if (typeof value !== 'string') return value;
    return knownValues[value] || value;
  }

  window.__1122_UI_TEXT__ = Object.freeze({
    status: mapKnownValue,
    staticValue: mapKnownValue
  });
})();
