-- Seed user operating experience into 1122 Knowledge Base.
-- These records describe the user's observed/derived operating experience.
-- They are NOT automatically equivalent to Amazon policy or confirmed universal truth.

INSERT OR IGNORE INTO knowledge_items (
  knowledge_id, record_version, is_current, knowledge_type, domain, subdomain, marketplace,
  title, summary, content, keywords_json, applicable_conditions_json,
  not_applicable_conditions_json, related_product_refs_json, related_knowledge_refs_json,
  source_refs_json, source_urls_json, truth_class, confidence, freshness_status,
  effective_at, last_verified_at, status, ui_visibility,
  execution_authorized, production_write_authorized, source_payload_json, source_version
) VALUES
('KB-ADS-0001',1,1,'ADVERTISING_KNOWLEDGE','Amazon Ads','Campaign Structure','US',
 'Exact / Phrase / Broad 分层投放并独立观察',
 '用户在 Amazon 广告中习惯将 Exact、Phrase、Broad 拆开管理，避免三种匹配方式的数据与动作混在一起。',
 '用户的实际广告管理思路是把 Exact、Phrase、Broad 拆成独立结构，分别观察搜索词扩展、转化和花费，再执行保留、降价、暂停、拉 Exact、否定或继续观察。该知识描述用户当前的运营习惯，不等于所有商品都必须采用同样结构。',
 '["Exact","Phrase","Broad","Amazon Ads","广告结构","匹配方式"]',
 '["需要区分不同匹配方式表现","需要从发现流量逐步沉淀高意向关键词"]',
 '["样本量极低且拆分后无法形成有效数据"]',
 '["Light Up Crochet Hook Set","Mahjong"]','[]',
 '["USER_OPERATING_EXPERIENCE:AmazonAds:ExactPhraseBroad"]','[]',
 'OBSERVED','HIGH','FRESH','2026-09-05','2026-09-05','ACTIVE',1,0,0,
 '{"owner_scope":"USER_OPERATING_EXPERIENCE"}','UserOperatingExperience.v1'),

('KB-ADS-0002',1,1,'ADVERTISING_KNOWLEDGE','Amazon Ads','Broad Discovery','US',
 'Broad 阶段采用一词一组以提高可控性',
 '用户在 Broad 探索阶段倾向采用一词一广告组，便于单独控制预算、竞价和否定。',
 '用户已明确采用 Broad 一词一组的结构。该结构的经营价值主要是提高搜索词扩展的归因和竞价控制精度，并方便把有效搜索词迁移到 Exact、把明显无效流量做否定。其成本是广告组数量增加、维护复杂度更高。',
 '["Broad","一词一组","search term discovery","广泛匹配","否定词"]',
 '["Broad 关键词数量可控","运营愿意进行较细颗粒度维护"]',
 '["关键词规模过大导致维护成本明显高于收益"]',
 '["Light Up Crochet Hook Set"]','["KB-ADS-0001"]',
 '["USER_OPERATING_EXPERIENCE:AmazonAds:BroadOneKeywordPerGroup"]','[]',
 'OBSERVED','HIGH','FRESH','2026-09-05','2026-09-05','ACTIVE',1,0,0,
 '{"owner_scope":"USER_OPERATING_EXPERIENCE"}','UserOperatingExperience.v1'),

('KB-ADS-0003',1,1,'DECISION_RULE','Amazon Ads','Keyword Promotion','US',
 '发现流量中的有效搜索词继续向 Exact 沉淀',
 '用户的关键词推进方式不是长期只留在发现层，而是把表现较好的实际搜索词进一步拉入 Exact 管理。',
 '在 Phrase/Broad/Auto 等发现型流量中，如果实际搜索词获得足够点击、订单或转化信号，用户会考虑单独拉到 Exact，并在原发现层根据流量重叠情况决定否定或保留。相反，持续消耗而无转化的词进入降价、否定、暂停或继续观察队列。',
 '["search term","拉Exact","关键词晋级","否定","降价","暂停"]',
 '["存在可识别的实际搜索词表现数据"]',
 '["点击与订单样本不足以支持判断"]',
 '[]','["KB-ADS-0001","KB-ADS-0002"]',
 '["USER_OPERATING_EXPERIENCE:AmazonAds:PromoteSearchTermToExact"]','[]',
 'DERIVED','HIGH','FRESH','2026-09-05','2026-09-05','ACTIVE',1,0,0,
 '{"owner_scope":"USER_OPERATING_EXPERIENCE"}','UserOperatingExperience.v1'),

('KB-PRI-0001',1,1,'PRICING_KNOWLEDGE','Amazon Pricing','Reference Price','US',
 '参考价变化会直接影响促销空间，定价不能只看当前成交价',
 '用户在实际经营中高度关注 List Price / Was Price / Your Price / Sale Price 对 Prime Discount、BD 等促销价格上限的联动。',
 '用户的定价经验是先识别当前被 Amazon 采用的参考价，再推导可用促销空间，而不是只看卖家后台输入的标价。用户曾观察到原始 List Price/Your Price 与后续 Sale Price、Was Price 的变化可能导致划线价和活动价格空间发生变化。该项属于用户经营观察，具体比例和 Amazon 当前计算规则必须继续由 APB/官方政策实时验证。',
 '["List Price","Was Price","Your Price","Sale Price","BD","Prime Discount","参考价"]',
 '["需要规划 Prime Discount、BD、Deal 或站内折扣"]',
 '["把历史观察直接当作当前 Amazon 固定政策比例"]',
 '[]','[]',
 '["USER_OPERATING_EXPERIENCE:Pricing:ReferencePriceFirst"]','[]',
 'OBSERVED','HIGH','FRESH','2026-09-05','2026-09-05','ACTIVE',1,0,0,
 '{"owner_scope":"USER_OPERATING_EXPERIENCE"}','UserOperatingExperience.v1'),

('KB-CAS-0001',1,1,'CASE_LESSON','Amazon Pricing','Reference Price Case','US',
 '高价短期成交后降到 Sale Price，划线价仍可能丢失',
 '用户真实案例中，99.99 美元先成交数单，随后以 69.99 美元连续出单，最终观察到划线价丢失、Was Price 向较低成交区间变化。',
 '该案例说明少量高价成交并不能保证较高参考价长期保持。后续较低价格的持续成交可能改变 Amazon 对历史价格的识别。这个案例只记录真实现象，不直接推导 Amazon 的唯一算法；后续策略仍需结合当期参考价、历史价格和活动规则验证。',
 '["99.99","69.99","Was Price","划线价","历史成交价","案例"]',
 '["分析参考价为何变化","评估长期低价成交对后续活动空间的影响"]','[]',
 '[]','["KB-PRI-0001"]',
 '["USER_CASE:Pricing:99.99_to_69.99_reference_price_loss"]','[]',
 'OBSERVED','HIGH','FRESH','2026-09-05','2026-09-05','ACTIVE',1,0,0,
 '{"owner_scope":"USER_OPERATING_EXPERIENCE"}','UserOperatingExperience.v1'),

('KB-DEC-0001',1,1,'DECISION_RULE','Inventory','Clearance Decision','US',
 '清库存决策必须比较继续销售总损失与立即退出总损失',
 '用户在滞销库存处理中要求把仓储费、广告费、产品成本、售价、折扣和预计售完时间放在同一损益模型里，而不是只看单件毛利。',
 '用户的库存退出判断方法是同时建立至少两个方案：立即清仓/清货，与继续销售直到预计售罄。比较时纳入产品成本、Amazon费用、广告占比、折扣后成交价、未来仓储费、旺季仓储变化、预计销量节奏和时间价值。最终选择总亏损更低或风险更可控的方案。',
 '["清库存","清货","仓储费","广告费","总亏损","退出策略","库存风险"]',
 '["库存滞销","临近高仓储费周期","需要决定清货或继续销售"]',
 '["只比较单件售价而忽略时间与仓储成本"]',
 '[]','[]',
 '["USER_OPERATING_EXPERIENCE:Inventory:CompareTotalLossScenarios"]','[]',
 'DERIVED','HIGH','FRESH','2026-09-05','2026-09-05','ACTIVE',1,0,0,
 '{"owner_scope":"USER_OPERATING_EXPERIENCE"}','UserOperatingExperience.v1'),

('KB-CAS-0002',1,1,'CASE_LESSON','Amazon Ads','Keyword Failure Case','US',
 'travel mahjong set 61 次点击无转化应进入异常词处理队列',
 '用户的麻将广告中，travel mahjong set 曾出现 61 次点击无转化，是明确的高消耗无转化案例。',
 '该案例应被系统用于训练广告异常识别：当关键词累积大量点击仍无订单时，不能继续仅凭相关性维持原竞价，应结合搜索意图、Listing匹配度、价格、主图和商品形态检查，并进入降价、暂停、否定或重新定义投放角色的决策队列。61 点击是该具体案例事实，不应机械复制为所有产品统一阈值。',
 '["travel mahjong set","61 clicks","无转化","广告异常","麻将"]',
 '["高点击无订单关键词诊断"]',
 '["把 61 点击机械设为全品类统一停词阈值"]',
 '["Mahjong"]','["KB-ADS-0003"]',
 '["USER_CASE:Ads:travel_mahjong_set_61_clicks_zero_order"]','[]',
 'OBSERVED','HIGH','FRESH','2026-09-05','2026-09-05','ACTIVE',1,0,0,
 '{"owner_scope":"USER_OPERATING_EXPERIENCE"}','UserOperatingExperience.v1'),

('KB-CON-0001',1,1,'CONTENT_KNOWLEDGE','Amazon Listing','Main Image CTR','US',
 'CTR 低时先检查主图的信息优先级和核心差异点是否一眼可见',
 '用户在 Light Up Crochet Hook Set 的低 CTR 问题中，把主图与标题的第一屏表达作为优先优化对象，而不是只通过提高广告竞价解决。',
 '当广告有曝光但 CTR 低时，用户会优先检查白底主图中的核心产品、关键附件和差异化卖点是否清晰，以及标题前段是否快速表达产品是什么。该经验尤其适用于功能型新品。是否提升 CTR 必须用修改前后数据验证，不能把视觉改版本身当作效果已确认。',
 '["CTR","主图","标题","第一屏","Light Up Crochet Hook Set","转化前链路"]',
 '["曝光存在但 CTR 偏低","产品差异点在搜索结果页不够明显"]',
 '["曝光本身极低，尚无法判断 CTR 问题"]',
 '["Light Up Crochet Hook Set","B0H6X5Q4PL"]','[]',
 '["USER_OPERATING_EXPERIENCE:Listing:CTRFirstScreenDiagnosis"]','[]',
 'OBSERVED','MEDIUM','FRESH','2026-09-05','2026-09-05','ACTIVE',1,0,0,
 '{"owner_scope":"USER_OPERATING_EXPERIENCE"}','UserOperatingExperience.v1');
